M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-09-14T23:27:36+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T23:27:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.400
%
G90
G05
T1
X68.46Y-6.0
X73.54Y-4.984
X73.54Y-7.016
T2
X54.5Y-8.55
T3
X3.98Y-10.64
X3.98Y-21.34
T4
X6.2Y4.0
X6.2Y-45.287
X63.0Y4.0
X63.0Y-45.264
M30
